// Generated by gencpp from file hector_uav_msgs/EnableMotors.msg
// DO NOT EDIT!


#ifndef HECTOR_UAV_MSGS_MESSAGE_ENABLEMOTORS_H
#define HECTOR_UAV_MSGS_MESSAGE_ENABLEMOTORS_H

#include <ros/service_traits.h>


#include <hector_uav_msgs/EnableMotorsRequest.h>
#include <hector_uav_msgs/EnableMotorsResponse.h>


namespace hector_uav_msgs
{

struct EnableMotors
{

typedef EnableMotorsRequest Request;
typedef EnableMotorsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EnableMotors
} // namespace hector_uav_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hector_uav_msgs::EnableMotors > {
  static const char* value()
  {
    return "6a0b406242562fc416b2c9c8a3efb051";
  }

  static const char* value(const ::hector_uav_msgs::EnableMotors&) { return value(); }
};

template<>
struct DataType< ::hector_uav_msgs::EnableMotors > {
  static const char* value()
  {
    return "hector_uav_msgs/EnableMotors";
  }

  static const char* value(const ::hector_uav_msgs::EnableMotors&) { return value(); }
};


// service_traits::MD5Sum< ::hector_uav_msgs::EnableMotorsRequest> should match 
// service_traits::MD5Sum< ::hector_uav_msgs::EnableMotors > 
template<>
struct MD5Sum< ::hector_uav_msgs::EnableMotorsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hector_uav_msgs::EnableMotors >::value();
  }
  static const char* value(const ::hector_uav_msgs::EnableMotorsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hector_uav_msgs::EnableMotorsRequest> should match 
// service_traits::DataType< ::hector_uav_msgs::EnableMotors > 
template<>
struct DataType< ::hector_uav_msgs::EnableMotorsRequest>
{
  static const char* value()
  {
    return DataType< ::hector_uav_msgs::EnableMotors >::value();
  }
  static const char* value(const ::hector_uav_msgs::EnableMotorsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hector_uav_msgs::EnableMotorsResponse> should match 
// service_traits::MD5Sum< ::hector_uav_msgs::EnableMotors > 
template<>
struct MD5Sum< ::hector_uav_msgs::EnableMotorsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hector_uav_msgs::EnableMotors >::value();
  }
  static const char* value(const ::hector_uav_msgs::EnableMotorsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hector_uav_msgs::EnableMotorsResponse> should match 
// service_traits::DataType< ::hector_uav_msgs::EnableMotors > 
template<>
struct DataType< ::hector_uav_msgs::EnableMotorsResponse>
{
  static const char* value()
  {
    return DataType< ::hector_uav_msgs::EnableMotors >::value();
  }
  static const char* value(const ::hector_uav_msgs::EnableMotorsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HECTOR_UAV_MSGS_MESSAGE_ENABLEMOTORS_H
